### ISSUE TITLE
confusion about SCADE metrics

### ISSUE THREAD

**Issue by yulunwu0108** [XT5un/P2NeRF#1]
Congratulations on your acceptance! I find that in the paper you point out
> In the official implementation of SCADE, the rendering images are post-processed with ground truth. For fair comparisons, we just report the results without post-processing.

Could you please give a further instruction of how they did the post-processing or the location of the processing code? Thanks very much.

**Comment by XT5un** [comment]
The SCADE code has fixed this issue (https://github.com/mikacuy/scade/commit/23139b164461169e32121234696df88580c3d644). In previous versions, SCADE would calculate a least squares transformation between **_GT_** and **_pred_** before evaluating the image metrics. We used the previous version of the SCADE for our comparison and removed that transform to ensure a consistent comparison with other methods.

**Comment by yulunwu0108** [comment]
OK, I understand it now. Thank you!
