### ISSUE TITLE
Why you disable anneal nearfar in conf?

### ISSUE THREAD

**Issue by DaLi-Jack** [XT5un/P2NeRF#3]
Hi! Thanks for your great work!
I'm curious why you disabled 'anneal nearfar' in the [config](https://github.com/XT5un/P2NeRF/blob/5631035b67e8ac1131a4b95ee82190e187a43b10/configs/p2nerf/replica_p2nerf_full.gin#L58), as it has been shown to be beneficial in RegNeRF. Did you conduct experiments and find that it wasn't particularly effective on scene-level datasets, such as the Replica dataset?
Looking forward to your reply!

**Comment by XT5un** [comment]
This code is modified based on FreeNeRF, but we only use the network implementation from MipNeRF and do not use the regularization from FreeNeRF or RegNeRF.

In fact, you could try enabling these regularizations.

I experimented with an annealing strategy early on, but later found that using keypoint initialization worked better for scenes in ScanNet and Replica. However, I also found that the annealing strategy is quite effective on the DTU dataset, which I believe may be related to the depth distribution of the training views. The depth distribution in DTU is more concentrated, while the depth distribution in indoor scenes from ScanNet and Replica is more uneven. Additionally, the default annealing strategy starts optimization from the middle of the near and far planes. Many effective depths in DTU are close to this middle value, whereas the depths of many pixels in indoor scenes are not near this middle value, so early annealing does not yield many benefits.

**Comment by XT5un** [comment]
I don’t remember if the annealing strategy I added in the Replica dataloader is fully consistent with the original paper, so if you want to test annealing, you might need to check the code.

**Comment by DaLi-Jack** [comment]
Thanks for your quick and detailed reply! I completely agree with your point. Since scene-level datasets (i.e., Replica and ScanNet in your paper) are not captured around a specific object and lack a clear object center like in the DTU dataset, the anneal method might indeed be less effective on scene-level datasets.
Additionally, I have another question. In SparseNeRF, besides the depth rank loss, there is also a depth continuity loss. While your paper's group depth rank loss indeed replaces the depth rank loss in SparseNeRF, it seems that the depth continuity loss was not used. Did you conduct any experiments to determine whether the depth continuity loss could still provide improvements in your work?

**Comment by XT5un** [comment]
I think the depth continuity loss of SparseNeRF is also useful for our method. From the visualisation, our results are not locally smooth, and this might be improved by adding a depth smoothness constraint.

**Comment by DaLi-Jack** [comment]
Thanks again for your reply!
